### ISSUE TITLE
Add Conference Schedule

### ISSUE THREAD

**Issue by maxxcrawford** [tulsaux/uxok-website#52]

**Comment by emilyharden** [comment]
![Screenshot 2023-07-13 at 1 40 03 PM](https://github.com/tulsaux/uxok-website/assets/72417338/07fa2368-43b2-4ec9-bd62-f35e9e124daa)

**Comment by emilyharden** [comment]
<img width="777" alt="Screenshot 2023-07-13 at 3 29 05 PM" src="https://github.com/tulsaux/uxok-website/assets/72417338/76aff4a5-a4c5-4330-9ee9-e2fa20888739">
